### ISSUE TITLE
reserve a port using 'force' fails.

### ISSUE THREAD

**Issue by madhurabhogate** [shmir/PyIxNetwork#1]
>>> ixn.reserve({ixn.root.get_object_by_name('Ethernet - 001'): port1_location}, force=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/ixnetwork/ixn_app.py", line 113, in reserve
    port.release()
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/ixnetwork/ixn_port.py", line 66, in release
    self.execute('releasePort', [self.ref])
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/ixnetwork/ixn_object.py", line 140, in execute
    return self.api.execute(command, self.ref, *arguments)
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/ixnetwork/api/ixn_python.py", line 51, in execute
    return self.ixn.execute(command, *arguments)
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/IxNetwork.py", line 180, in execute
    return self.__SendRecv('ixNet', 'exec', *args)
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/IxNetwork.py", line 343, in __SendRecv
    return self.__Recv()
  File "/home/star/.virtualenvs/ixia_py36/lib/python3.6/site-packages/IxNetwork.py", line 428, in __Recv
    raise IxNetError(''.join(self._decoratedResult))
IxNet.IxNetError: ::ixNet::ERROR-No matching exec found, use the following command to list all execs: ixNet help execList -all
Closest matches are the following execs:
	releasePort (kArray[kObjref=/vport])

**Comment by shmir** [comment]
The python low level API is not fully supported at this point.
Please use tcl or REST as low level API.

**Comment by shmir** [comment]
Hello,
Did you manage to work with REST low level? I.e.


from trafficgenerator.tgn_utils import ApiType

self.ixn = init_ixn(api = ApiType.tcl, logger=logging.getLogger('log'))

Can this issue be closed?

Regards,
Yoram
